/* Automatically generated by wasm2c */
#ifndef GUNS_H_GENERATED_
#define GUNS_H_GENERATED_

#include "wasm-rt.h"

#include <stdint.h>

#ifndef WASM_RT_CORE_TYPES_DEFINED
#define WASM_RT_CORE_TYPES_DEFINED
typedef uint8_t u8;
typedef int8_t s8;
typedef uint16_t u16;
typedef int16_t s16;
typedef uint32_t u32;
typedef int32_t s32;
typedef uint64_t u64;
typedef int64_t s64;
typedef float f32;
typedef double f64;
#endif

#ifdef __cplusplus
extern "C" {
#endif

struct w2c_wbg;

typedef struct w2c_guns {
  struct w2c_wbg* w2c_wbg_instance;
  u32 w2c_g0;
  wasm_rt_memory_t w2c_memory;
  wasm_rt_funcref_table_t w2c_T0;
  wasm_rt_externref_table_t w2c_0x5F_wbindgen_export_2;
} w2c_guns;

void wasm2c_guns_instantiate(w2c_guns*, struct w2c_wbg*);
void wasm2c_guns_free(w2c_guns*);
wasm_rt_func_type_t wasm2c_guns_get_func_type(uint32_t param_count, uint32_t result_count, ...);

/* import: 'wbg' '__wbg_buffer_609cc3eee51ed158' */
wasm_rt_externref_t w2c_wbg_0x5F_wbg_buffer_609cc3eee51ed158(struct w2c_wbg*, wasm_rt_externref_t);

/* import: 'wbg' '__wbg_call_672a4d21634d4a24' */
wasm_rt_externref_t w2c_wbg_0x5F_wbg_call_672a4d21634d4a24(struct w2c_wbg*, wasm_rt_externref_t, wasm_rt_externref_t);

/* import: 'wbg' '__wbg_call_7cccdd69e0791ae2' */
wasm_rt_externref_t w2c_wbg_0x5F_wbg_call_7cccdd69e0791ae2(struct w2c_wbg*, wasm_rt_externref_t, wasm_rt_externref_t, wasm_rt_externref_t);

/* import: 'wbg' '__wbg_crypto_ed58b8e10a292839' */
wasm_rt_externref_t w2c_wbg_0x5F_wbg_crypto_ed58b8e10a292839(struct w2c_wbg*, wasm_rt_externref_t);

/* import: 'wbg' '__wbg_getRandomValues_bcb4912f16000dc4' */
void w2c_wbg_0x5F_wbg_getRandomValues_bcb4912f16000dc4(struct w2c_wbg*, wasm_rt_externref_t, wasm_rt_externref_t);

/* import: 'wbg' '__wbg_msCrypto_0a36e2ec3a343d26' */
wasm_rt_externref_t w2c_wbg_0x5F_wbg_msCrypto_0a36e2ec3a343d26(struct w2c_wbg*, wasm_rt_externref_t);

/* import: 'wbg' '__wbg_new_405e22f390576ce2' */
wasm_rt_externref_t w2c_wbg_0x5F_wbg_new_405e22f390576ce2(struct w2c_wbg*);

/* import: 'wbg' '__wbg_new_a12002a7f91c75be' */
wasm_rt_externref_t w2c_wbg_0x5F_wbg_new_a12002a7f91c75be(struct w2c_wbg*, wasm_rt_externref_t);

/* import: 'wbg' '__wbg_newnoargs_105ed471475aaf50' */
wasm_rt_externref_t w2c_wbg_0x5F_wbg_newnoargs_105ed471475aaf50(struct w2c_wbg*, u32, u32);

/* import: 'wbg' '__wbg_newwithbyteoffsetandlength_d97e637ebe145a9a' */
wasm_rt_externref_t w2c_wbg_0x5F_wbg_newwithbyteoffsetandlength_d97e637ebe145a9a(struct w2c_wbg*, wasm_rt_externref_t, u32, u32);

/* import: 'wbg' '__wbg_newwithlength_a381634e90c276d4' */
wasm_rt_externref_t w2c_wbg_0x5F_wbg_newwithlength_a381634e90c276d4(struct w2c_wbg*, u32);

/* import: 'wbg' '__wbg_node_02999533c4ea02e3' */
wasm_rt_externref_t w2c_wbg_0x5F_wbg_node_02999533c4ea02e3(struct w2c_wbg*, wasm_rt_externref_t);

/* import: 'wbg' '__wbg_process_5c1d670bc53614b8' */
wasm_rt_externref_t w2c_wbg_0x5F_wbg_process_5c1d670bc53614b8(struct w2c_wbg*, wasm_rt_externref_t);

/* import: 'wbg' '__wbg_randomFillSync_ab2cfe79ebbf2740' */
void w2c_wbg_0x5F_wbg_randomFillSync_ab2cfe79ebbf2740(struct w2c_wbg*, wasm_rt_externref_t, wasm_rt_externref_t);

/* import: 'wbg' '__wbg_require_79b1e9274cde3c87' */
wasm_rt_externref_t w2c_wbg_0x5F_wbg_require_79b1e9274cde3c87(struct w2c_wbg*);

/* import: 'wbg' '__wbg_set_65595bdd868b3009' */
void w2c_wbg_0x5F_wbg_set_65595bdd868b3009(struct w2c_wbg*, wasm_rt_externref_t, wasm_rt_externref_t, u32);

/* import: 'wbg' '__wbg_set_bb8cecf6a62b9f46' */
u32 w2c_wbg_0x5F_wbg_set_bb8cecf6a62b9f46(struct w2c_wbg*, wasm_rt_externref_t, wasm_rt_externref_t, wasm_rt_externref_t);

/* import: 'wbg' '__wbg_static_accessor_GLOBAL_88a902d13a557d07' */
u32 w2c_wbg_0x5F_wbg_static_accessor_GLOBAL_88a902d13a557d07(struct w2c_wbg*);

/* import: 'wbg' '__wbg_static_accessor_GLOBAL_THIS_56578be7e9f832b0' */
u32 w2c_wbg_0x5F_wbg_static_accessor_GLOBAL_THIS_56578be7e9f832b0(struct w2c_wbg*);

/* import: 'wbg' '__wbg_static_accessor_SELF_37c5d418e4bf5819' */
u32 w2c_wbg_0x5F_wbg_static_accessor_SELF_37c5d418e4bf5819(struct w2c_wbg*);

/* import: 'wbg' '__wbg_static_accessor_WINDOW_5de37043a91a9c40' */
u32 w2c_wbg_0x5F_wbg_static_accessor_WINDOW_5de37043a91a9c40(struct w2c_wbg*);

/* import: 'wbg' '__wbg_subarray_aa9065fa9dc5df96' */
wasm_rt_externref_t w2c_wbg_0x5F_wbg_subarray_aa9065fa9dc5df96(struct w2c_wbg*, wasm_rt_externref_t, u32, u32);

/* import: 'wbg' '__wbg_versions_c71aa1626a93e0a1' */
wasm_rt_externref_t w2c_wbg_0x5F_wbg_versions_c71aa1626a93e0a1(struct w2c_wbg*, wasm_rt_externref_t);

/* import: 'wbg' '__wbindgen_debug_string' */
void w2c_wbg_0x5F_wbindgen_debug_string(struct w2c_wbg*, u32, wasm_rt_externref_t);

/* import: 'wbg' '__wbindgen_init_externref_table' */
void w2c_wbg_0x5F_wbindgen_init_externref_table(struct w2c_wbg*);

/* import: 'wbg' '__wbindgen_is_function' */
u32 w2c_wbg_0x5F_wbindgen_is_function(struct w2c_wbg*, wasm_rt_externref_t);

/* import: 'wbg' '__wbindgen_is_object' */
u32 w2c_wbg_0x5F_wbindgen_is_object(struct w2c_wbg*, wasm_rt_externref_t);

/* import: 'wbg' '__wbindgen_is_string' */
u32 w2c_wbg_0x5F_wbindgen_is_string(struct w2c_wbg*, wasm_rt_externref_t);

/* import: 'wbg' '__wbindgen_is_undefined' */
u32 w2c_wbg_0x5F_wbindgen_is_undefined(struct w2c_wbg*, wasm_rt_externref_t);

/* import: 'wbg' '__wbindgen_memory' */
wasm_rt_externref_t w2c_wbg_0x5F_wbindgen_memory(struct w2c_wbg*);

/* import: 'wbg' '__wbindgen_number_new' */
wasm_rt_externref_t w2c_wbg_0x5F_wbindgen_number_new(struct w2c_wbg*, f64);

/* import: 'wbg' '__wbindgen_string_new' */
wasm_rt_externref_t w2c_wbg_0x5F_wbindgen_string_new(struct w2c_wbg*, u32, u32);

/* import: 'wbg' '__wbindgen_throw' */
void w2c_wbg_0x5F_wbindgen_throw(struct w2c_wbg*, u32, u32);

/* export: 'memory' */
wasm_rt_memory_t* w2c_guns_memory(w2c_guns* instance);

/* export: '__wbg_gunssolver_free' */
void w2c_guns_0x5F_wbg_gunssolver_free(w2c_guns*, u32, u32);

/* export: 'gunssolver_new' */
u32 w2c_guns_gunssolver_new(w2c_guns*, u32, u32, u32, u32, u32, u32, u32, u32);

/* export: 'gunssolver_solve_pow' */
wasm_rt_externref_t w2c_guns_gunssolver_solve_pow(w2c_guns*, u32);

/* export: '__wbindgen_exn_store' */
void w2c_guns_0x5F_wbindgen_exn_store(w2c_guns*, u32);

/* export: '__externref_table_alloc' */
u32 w2c_guns_0x5F_externref_table_alloc(w2c_guns*);

/* export: '__wbindgen_export_2' */
wasm_rt_externref_table_t* w2c_guns_0x5F_wbindgen_export_2(w2c_guns* instance);

/* export: '__wbindgen_malloc' */
u32 w2c_guns_0x5F_wbindgen_malloc(w2c_guns*, u32, u32);

/* export: '__wbindgen_realloc' */
u32 w2c_guns_0x5F_wbindgen_realloc(w2c_guns*, u32, u32, u32, u32);

/* export: '__wbindgen_start' */
void w2c_guns_0x5F_wbindgen_start(w2c_guns*);

#ifdef __cplusplus
}
#endif

#endif  /* GUNS_H_GENERATED_ */
