POST https://guns.lol/api/analytics/record
Content-Type: application/json

{
  "_t": "turnstile response",
  "_gpp_ch": [
    "oUAFFCgIIAUAAgEDBFRWE1Bbr_TxYzk5MjZmYWI4NTZkZjlhNjQ5YmY1MWM1NWUyOTk5ZDJmZjE1Y2ZiZGNjYjhjY2Q1YzgzNzMzNTc2NGIXqZPHa_eHIw",
    1767638499,
    "1867764c175fc766ce086157515853444b999d7f64d03cbe1d96b78cf6224e02",
    "Zn6F5oHCaRnX1vT9zQ81a4Ty7faAAGCb",
    {
      "_oo": "UQVkZTliMgAAAADV9yF_ff0_dA",
      "seal": "c99262fa9b856df9a649dbf51c55e299b9d2ff15ecfbdccb8ccd5c837335764b"
    }
  ],
  "username": "tenshiifemboy",
  "deviceType": "desktop",
  "event": "view",
  "linkId": null,
  "referrer": ""
}