POST https://guns.lol/api/analytics/record
Content-Type: application/json

{
  "_t": "turnstile",
  "_gpp_ch": [
    "oUAFGQstNwcAAwECBPAjukSjH1C7ZTIxMDk4OWFmOThlMGYyODYzYjhlZWRkMGNhMDQ4ODI0Y2Q4MmM5MDc2ZmM5ZjUzNTE2YzQ4MDc0NzOOPcUuvyL-DQ",
    1772912839,
    "249b9f4b80ff1ddc3a29beba2e32897b1cde3ae0a4f22e997aa15e1a18fbf90f",
    "AbY2Zd0ro2AtZPgFzftqG0r68pb9NmTp",
    "e2109895af918e0f2863b8eed9d0ca048824cd82c90768fc9f535163c4807473",
    "UQU5MTgzNQEAAAC2d9_3hPW6zw"
  ],
  "username": "tenshiifemboy",
  "deviceType": "desktop",
  "event": "view",
  "linkId": null,
  "referrer": "https://guns.lol/tenshiifemboy"
}